### ISSUE TITLE
create / view / delete / fork paste

### ISSUE THREAD

**Issue by MasseGuillaume** [OlegYch/scastie#11]

**Comment by MasseGuillaume** [comment]
I propose the following:
* every time you hit run it creates a paste
* to fork you visit the URL (ex: https://scastie.org/45) and you hit run
* pastes are immutable
  * you cannot delete them
  * you cannot edit them

**Comment by julienrf** [comment]
I’m afraid we will keep storing a lot of intermediate pastes (e.g. if one hits run every now and again between the time she creates the paste and the time she actually finished it).

**Comment by julienrf** [comment]
One solution could be to automatically expire pastes after some delay (like one month), and to have an explicit “publish” action that would prevent this expiration to happen.

**Comment by MasseGuillaume** [comment]
Yep with Scala.js it can be problematic at 1M / run. Let's keep this idea on the radar.
