### ISSUE TITLE
sbt ui

### ISSUE THREAD

**Issue by MasseGuillaume** [OlegYch/scastie#14]
- [x] libraryDependencies: scaladex #13 
- [x] scalaVersion
- [x] targets: radio jvm(scala 2.X or dotty), Scala.js(disabled), native(disabled)

postponed: #20

**Comment by OlegYch** [comment]
adding sbt plugins is possible
in theory we just need to apply logic from https://github.com/OlegYch/scastie/blob/master/renderer-template/project/ApplicationBuild.scala#L34 to https://github.com/OlegYch/scastie/blob/master/renderer-template/project/project/ApplicationBuild.scala
